# SPDX-FileCopyrightText: 2025-2026 Temple University <kleinweb@temple.edu>
#
# SPDX-License-Identifier: CC0-1.0

# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
---
name: Set up application

inputs:
  environment:
    # yamllint disable-line rule:line-length
    description: 'Target environment. One of: "production", "development", "staging".'
    default: "development"
  github_token:
    description: "GitHub API token"

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ inputs.github_token }}
