# SPDX-FileCopyrightText: 2025-2026 Temple University <kleinweb@temple.edu>
#
# SPDX-License-Identifier: CC0-1.0

# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
---
name: Setup Nix

inputs:
  devshell:
    description: "Name of the devshell to use for CI tasks."
    default: "ci"
  github_token:
    description: "GitHub API token to prevent rate limiting."
  cachix_auth_token:
    description: "Cachix authentication token for cache writes."

runs:
  using: composite
  steps:
    - name: Install Nix
      uses: cachix/install-nix-action@v30
      with:
        github_access_token: ${{ inputs.github_token }}

    - name: Setup binary cache
      uses: cachix/cachix-action@v15
      with:
        name: kleinweb
        extraPullNames: dotfield,nix-community
        authToken: ${{ inputs.cachix_auth_token }}

    - uses: DeterminateSystems/magic-nix-cache-action@v8

    - name: "Initialize Nix CI shell"
      uses: nicknovitski/nix-develop@v1
      with:
        arguments: "#${{ inputs.devshell }}"
